ALTER TABLE EX1_023527.ADDRESSES
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.ADDRESSES CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.ADDRESSES
(
  ADDRESS_ID  NUMBER                            NOT NULL,
  ADDRESS_TY  VARCHAR2(100 BYTE),
  STREET      VARCHAR2(255 BYTE),
  ZIPCODE     VARCHAR2(100 BYTE),
  CITY_ID     NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023527.BILLING
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.BILLING CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.BILLING
(
  BIL_ADDRESS_ID  NUMBER                        NOT NULL,
  BIL_STREET      VARCHAR2(255 BYTE),
  CITY_ID         NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE EX1_023527.CITIES CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.CITIES
(
  CITY_ID  NUMBER,
  NAME     VARCHAR2(100 BYTE),
  STATE    VARCHAR2(100 BYTE),
  COUNTRY  VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE EX1_023527.CUSTOMERS CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.CUSTOMERS
(
  CUSTOMER_ID     NUMBER,
  FIRST_NAME      VARCHAR2(100 BYTE),
  LAST_NAME       VARCHAR2(100 BYTE),
  COMPANY         VARCHAR2(100 BYTE),
  EMAIL           VARCHAR2(100 BYTE),
  BIL_ADDRESS_ID  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023527.ORDERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.ORDERS CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.ORDERS
(
  ORDER_ID     NUMBER                           NOT NULL,
  ORDER_DATE   DATE,
  SHIP_ID      NUMBER,
  TAX          NUMBER,
  SUBTOTAL     NUMBER,
  ADDRESS_ID   NUMBER,
  CUSTOMER_ID  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023527.ORDERS_PRODUCTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.ORDERS_PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.ORDERS_PRODUCTS
(
  ORDER_PROD_ID    NUMBER                       NOT NULL,
  ORDER_QTY        NUMBER,
  ORDER_ID         NUMBER,
  PROD_ID          NUMBER,
  UNIT_PRICE       NUMBER,
  UNIT_PRICE_DISC  NUMBER(23,2)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023527.PRODUCTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.PRODUCTS CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.PRODUCTS
(
  PROD_ID       NUMBER                          NOT NULL,
  PROD_NAME     VARCHAR2(100 BYTE),
  PROD_COLOR    VARCHAR2(100 BYTE),
  LIST_PRICE    NUMBER(23,2),
  PROD_SIZE     VARCHAR2(10 BYTE),
  PROD_WEIGHT   VARCHAR2(10 BYTE),
  PROD_CAT      VARCHAR2(100 BYTE),
  CULTURE       VARCHAR2(10 BYTE),
  CULTURE_DESC  VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE EX1_023527.SHIPPING
 DROP PRIMARY KEY CASCADE;

DROP TABLE EX1_023527.SHIPPING CASCADE CONSTRAINTS;

CREATE TABLE EX1_023527.SHIPPING
(
  SHIP_ID      NUMBER                           NOT NULL,
  SHIP_METHOD  VARCHAR2(100 BYTE),
  SHIPPING     NUMBER(23,2)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX EX1_023527.ADDRESSES_PK ON EX1_023527.ADDRESSES
(ADDRESS_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023527.BILLING_PK ON EX1_023527.BILLING
(BIL_ADDRESS_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023527.ORDERS_PK ON EX1_023527.ORDERS
(ORDER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023527.ORDERS_PRODUCTS_PK ON EX1_023527.ORDERS_PRODUCTS
(ORDER_PROD_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023527.PRODUCTS_PK ON EX1_023527.PRODUCTS
(PROD_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX EX1_023527.SHIPPING_PK ON EX1_023527.SHIPPING
(SHIP_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE EX1_023527.ADDRESSES ADD (
  CONSTRAINT ADDRESSES_PK
  PRIMARY KEY
  (ADDRESS_ID)
  USING INDEX EX1_023527.ADDRESSES_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.BILLING ADD (
  CONSTRAINT BILLING_PK
  PRIMARY KEY
  (BIL_ADDRESS_ID)
  USING INDEX EX1_023527.BILLING_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.ORDERS ADD (
  CONSTRAINT ORDERS_PK
  PRIMARY KEY
  (ORDER_ID)
  USING INDEX EX1_023527.ORDERS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.ORDERS_PRODUCTS ADD (
  CONSTRAINT ORDERS_PRODUCTS_PK
  PRIMARY KEY
  (ORDER_PROD_ID)
  USING INDEX EX1_023527.ORDERS_PRODUCTS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.PRODUCTS ADD (
  CONSTRAINT PRODUCTS_PK
  PRIMARY KEY
  (PROD_ID)
  USING INDEX EX1_023527.PRODUCTS_PK
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.SHIPPING ADD (
  CONSTRAINT SHIPPING_PK
  PRIMARY KEY
  (SHIP_ID)
  USING INDEX EX1_023527.SHIPPING_PK
  ENABLE VALIDATE);
DROP SEQUENCE EX1_023527.ADDRESS_SEQ;

CREATE SEQUENCE EX1_023527.ADDRESS_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.BIL_SEQ;

CREATE SEQUENCE EX1_023527.BIL_SEQ
  START WITH 2000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.CITY_SEQ;

CREATE SEQUENCE EX1_023527.CITY_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.CUSTOMER_SEQ;

CREATE SEQUENCE EX1_023527.CUSTOMER_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.ORDER_SEQ;

CREATE SEQUENCE EX1_023527.ORDER_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.ORD_PROD_SEQ;

CREATE SEQUENCE EX1_023527.ORD_PROD_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.PROD_SEQ;

CREATE SEQUENCE EX1_023527.PROD_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE EX1_023527.SHIP_SEQ;

CREATE SEQUENCE EX1_023527.SHIP_SEQ
  START WITH 1000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE EX1_023527.ADDRESSES
  DROP CONSTRAINT ADDRESSES_R01;

ALTER TABLE EX1_023527.ADDRESSES
  DROP CONSTRAINT ADDRESSES_PK;

ALTER TABLE EX1_023527.ADDRESSES ADD (
  CONSTRAINT ADDRESSES_PK
  PRIMARY KEY
  (ADDRESS_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.BILLING
  DROP CONSTRAINT BILLING_PK;

ALTER TABLE EX1_023527.BILLING ADD (
  CONSTRAINT BILLING_PK
  PRIMARY KEY
  (BIL_ADDRESS_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.CITIES
  DROP CONSTRAINT CITIES_PK;

ALTER TABLE EX1_023527.CITIES ADD (
  CONSTRAINT CITIES_PK
  PRIMARY KEY
  (CITY_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.CUSTOMERS
  DROP CONSTRAINT CUSTOMERS_R01;

ALTER TABLE EX1_023527.CUSTOMERS
  DROP CONSTRAINT CUSTOMERS_PK;

ALTER TABLE EX1_023527.CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_PK
  PRIMARY KEY
  (CUSTOMER_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.ORDERS
  DROP CONSTRAINT ORDERS_R01;

ALTER TABLE EX1_023527.ORDERS
  DROP CONSTRAINT ORDERS_R02;

ALTER TABLE EX1_023527.ORDERS
  DROP CONSTRAINT ORDERS_R03;

ALTER TABLE EX1_023527.ORDERS
  DROP CONSTRAINT ORDERS_PK;

ALTER TABLE EX1_023527.ORDERS ADD (
  CONSTRAINT ORDERS_PK
  PRIMARY KEY
  (ORDER_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.ORDERS_PRODUCTS
  DROP CONSTRAINT ORDERS_PRODUCTS_R01;

ALTER TABLE EX1_023527.ORDERS_PRODUCTS
  DROP CONSTRAINT ORDERS_PRODUCTS_R02;

ALTER TABLE EX1_023527.ORDERS_PRODUCTS
  DROP CONSTRAINT ORDERS_PRODUCTS_PK;

ALTER TABLE EX1_023527.ORDERS_PRODUCTS ADD (
  CONSTRAINT ORDERS_PRODUCTS_PK
  PRIMARY KEY
  (ORDER_PROD_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.PRODUCTS
  DROP CONSTRAINT PRODUCTS_PK;

ALTER TABLE EX1_023527.PRODUCTS ADD (
  CONSTRAINT PRODUCTS_PK
  PRIMARY KEY
  (PROD_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.SHIPPING
  DROP CONSTRAINT SHIPPING_PK;

ALTER TABLE EX1_023527.SHIPPING ADD (
  CONSTRAINT SHIPPING_PK
  PRIMARY KEY
  (SHIP_ID)
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.ADDRESSES ADD (
  CONSTRAINT ADDRESSES_R01 
  FOREIGN KEY (CITY_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_R01 
  FOREIGN KEY (BIL_ADDRESS_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.ORDERS ADD (
  CONSTRAINT ORDERS_R01 
  FOREIGN KEY (ADDRESS_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.ORDERS ADD (
  CONSTRAINT ORDERS_R02 
  FOREIGN KEY (CUSTOMER_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.ORDERS ADD (
  CONSTRAINT ORDERS_R03 
  FOREIGN KEY (SHIP_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);


ALTER TABLE EX1_023527.ORDERS_PRODUCTS ADD (
  CONSTRAINT ORDERS_PRODUCTS_R01 
  FOREIGN KEY (ORDER_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);

ALTER TABLE EX1_023527.ORDERS_PRODUCTS ADD (
  CONSTRAINT ORDERS_PRODUCTS_R02 
  FOREIGN KEY (PROD_ID) 
  REFERENCES EX1_023527.
  ENABLE VALIDATE);